language: go

os:
  - linux

go:
  - 1.5.3

env:
  global:
    - GO15VENDOREXPERIMENT=1
    - PROJ="github.com/andrewkroh/dns-made-easy-updater"

sudo: false

before_install:
  # Put project into proper GOPATH location (important for forks).
  - mkdir -p $HOME/gopath/src/${PROJ}
  - rsync -az ${TRAVIS_BUILD_DIR}/ $HOME/gopath/src/${PROJ}/
  - export TRAVIS_BUILD_DIR=$HOME/gopath/src/${PROJ}
  - cd $HOME/gopath/src/${PROJ}

install:
  - go get github.com/mitchellh/gox

script:
  - gofmt -l *.go | read && echo "Code differs from gofmt's style. Run 'gofmt -w .'" 1>&2 && exit 1 || true
  - mkdir -p build/bin
  - gox -output="build/bin/{{.Dir}}_{{.OS}}_{{.Arch}}"

deploy:
  provider: releases
  file:
    - "$HOME/gopath/src/${PROJ}/build/bin/dns-made-easy-updater_darwin_386"
    - "$HOME/gopath/src/${PROJ}/build/bin/dns-made-easy-updater_darwin_amd64"
    - "$HOME/gopath/src/${PROJ}/build/bin/dns-made-easy-updater_freebsd_386"
    - "$HOME/gopath/src/${PROJ}/build/bin/dns-made-easy-updater_freebsd_amd64"
    - "$HOME/gopath/src/${PROJ}/build/bin/dns-made-easy-updater_freebsd_arm"
    - "$HOME/gopath/src/${PROJ}/build/bin/dns-made-easy-updater_linux_386"
    - "$HOME/gopath/src/${PROJ}/build/bin/dns-made-easy-updater_linux_amd64"
    - "$HOME/gopath/src/${PROJ}/build/bin/dns-made-easy-updater_linux_arm"
    - "$HOME/gopath/src/${PROJ}/build/bin/dns-made-easy-updater_netbsd_386"
    - "$HOME/gopath/src/${PROJ}/build/bin/dns-made-easy-updater_netbsd_amd64"
    - "$HOME/gopath/src/${PROJ}/build/bin/dns-made-easy-updater_netbsd_arm"
    - "$HOME/gopath/src/${PROJ}/build/bin/dns-made-easy-updater_openbsd_386"
    - "$HOME/gopath/src/${PROJ}/build/bin/dns-made-easy-updater_openbsd_amd64"
    - "$HOME/gopath/src/${PROJ}/build/bin/dns-made-easy-updater_windows_386.exe"
    - "$HOME/gopath/src/${PROJ}/build/bin/dns-made-easy-updater_windows_amd64.exe"
  api_key:
    secure: JPJ/X9uBaWSRXdWmrT9fUFXu1GymlgQu37JYUaTxpLbZNlPZj17YVKLTxmvgB27w6jJkKYCZ04sT9MUXkQo9RNFdHTVhVm+liHKVdUdYjHh4DyyvLJTt4LzpC8Ng7RqE4ULg2kTGlM/ZNIrjyT3Zj+Qoydv9Y7MvtXB18ksS+ERO7rm3s8lfvly7lFc2jzCsuJK9UgGqrsyJTh9k2froxaH+/Cewg3I/qHiXq3gKn8ziAHZNBFCjkZNw3gRrdR160BuAWwQR1eyRIVMi9V2pYySnHyrFDlLVQX4VsUTF44Ces5fo+5r/vdI85YLz0dPQ5zzpclfaPyl1ub7666udHE33+9cdgRn8etnVSNYWG3dfCoDLuw5nO6zfeuB2bJ0pHkPplNKhjmcHyP9T6EdGwN9VBx5hnw70a+nvJ3p8B1gek4eFke+LGGndCD4KDlC8sr+t4ZdCB6JMEp/0bcPPaVopr1CxSBPBKWmY/pTh9OxGaSa0oAwKudEt2HkfLxE/7TuUf7NXKVQqbcbBOKfeYXQydnYOl+1rKU+vfBQ2pp2vR4EoCZkM/XBd5SMWdinCqdxZjsY/F/lwbA3X7epkO+rFuQBjt9s+aftqt6MO99xhFAPxnm23NCCW0csSlkEbodWNsMKlhQZ8NF+jQ5PxvkSq9a/It9+alALUhyC/y08=
  on:
    tags: true
    repo: andrewkroh/dns-made-easy-updater
